name: Docker CI/CD

on:
  push:
    branches:
      - master  # Change this if using a different branch
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.PASSWORD }}" | docker login -u "${{ secrets.USERNAME }}" --password-stdin

      - name: Build and Push Backend Image
        run: |
          docker build -t ${{ secrets.USERNAME }}/ecommerce-backend:latest ./backend
          docker push ${{ secrets.USERNAME }}/ecommerce-backend:latest

      - name: Build and Push Frontend Image
        run: |
          docker build -t ${{ secrets.USERNAME }}/ecommerce-frontend:latest ./frontend
          docker push ${{ secrets.USERNAME }}/ecommerce-frontend:latest

      - name: Log out from Docker Hub
        run: docker logout
